import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"
import { container } from "@styled-system/patterns"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const pretendard = localFont({
  src: "../../public/font/PretendardGOVVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable}`}>
      <body
        className={container({
          maxW: "6xl",
          py: 8,
          minH: "100vh",
          bg: "background",
          fontFamily: "var(--font-pretendard)",
        })}>
        {children}
      </body>
    </html>
  )
}
