import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"
import { css } from "@styled-system/css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const pretendard = localFont({
  src: "../../static/font/PretendardGOVVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable}`}>
      <body
        className={css({ minH: "100vh", bg: "background", fontFamily: "var(--font-pretendard)" })}>
        {children}
      </body>
    </html>
  )
}
